spring.application.name=api-rest
server.port=8092

#config base de datos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://localhost:5433/db_ecommerce

#config hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#config openapi swagger
springdoc.swagger-ui.path=/swagger-ui-custom.html




