spring.application.name=api-rest
server.port=8092

#config base de datos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=
spring.datasource.url=jdbc:postgresql://localhost/db_ecommerce

#config hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




